### ISSUE TITLE
Before the HOL - deployment fails on notebookWorkspaces

### ISSUE THREAD

**Issue by zagruby** [microsoft/MCW-AI-led-business-process-automation#3]
Deployment of Before the HOL Azure Template fails for 'west europe' and 'east us', the resource resposible for the failure:

Microsoft.DocumentDB/databaseAccounts/notebookWorkspaces

Error messages I was getting:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"The requested region 'west europe' is not supported.\r\nActivityId: 69f157d6-8a0c-4acb-80c0-6ea672d0bbeb, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0"}]}

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"The requested region 'east us' is not supported.\r\nActivityId: aa4a4b00-2f24-4807-9ca1-98dbb3302162, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0"}]}

Edit: 
I was able to finish the HOL despite the error during the deployment. Great HOL:)

**Comment by DawnmarieDesJardins** [comment]
@codingbandit - Any update on this one?  Thank you!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #4
